#site conf
title: Yufei Chen
description: <span>Action</span> speak louder than words.

#user profile
user_name: Yufei(Andy) Chen
twitter: C_YF
facebook: chanyufei
github: chanyufei
email: umche355@myumanitoba.ca

gravatar_HASH: dcf2fa54d9a15ac67000c4b71abc07e6


pygments: true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
